---
- hosts: dbl
  become: yes
  gather_facts: False

  tasks:
  - name: Cron job for "df -h >> /tmp/diskspace" on the nodes at 5am and 5pm.
    cron:
      name: "Cron for Disk Space monitor"
      minute: "0"
      hour: "5,17"
      job: "df -h >> /tmp/diskspace"

  - name: List the cron jobs
    shell: crontab -l
    register: cron
  - debug:
      msg: "Message out {{ cron.stdout  }} "
  - debug: msg="Error {{ cron.stderr }}"
