---
- name: Install httpd package
  yum:
    name: httpd
    state: present
  register: httpdout
#- debug:
#    msg: "{{}}"
   
- name: Start httpd
  service:
    name: httpd
    state: started
  register: httpdstr
#- debug:
 #   msg: "{{ httpdstr }}"
   
- name: Open port for http
  firewalld:
    service: http
    permanent: true
    state: enabled
  register: httpenbl
#- debug:
#   msg: "{{ httpenbl }}"
   
- name: Restart firewalld
  service:
    name: firewalld
    state: reloaded
  register: firewalldout
#- debug:
#    msg: "{{ firewalldout }}"
