--- 
- hosts: localhost 
  gather_facts: true
  
  
  vars_files: 
  - /etc/ansible/AWS_LAB_ANSIBLE/key_files
  
  tasks: 
  - name: Checking the EC2-Ins status
    ec2_instance_info: 
      aws_access_key: "{{ aws_access_key }}"
      aws_region: "{{ aws_region }}"
      aws_secret_key: "{{ aws_secret_key }}"
    register: output
  
  - debug: 
    msg: output.instances

