---
- hosts: lb
  become: yes
  gather_facts: true
  
  tasks:
  - name: install the listed  {{ packages.name }} 
    yum:
      name: "{{ packages.name }}"
      state: present
    when: packages.required == true
