---
- hosts: db
  become: yes
  gather_facts: true
  
  tasks:
  - name: install the listed packages...
    yum:
      name: "{{ packages.name }}"
      state: present
    when: 
      - "{{ packages.required }} == true"
