---
- hosts: web
  become: yes

  tasks:
    - name: Intalling HTTD-Apache server using Dist. OS
      ansible.builtin.yum:
        name: httpd
        state: present
      when: ansible_distribution == "CentOS"
      register: httpdout
    - debug:
        msg: "{{ httpdout }}"
    - name: Intalling HTTD-Apach-2 server using Dist. OS
        ansible.builtin.yum:
        name: httpd
        state: present
      when: ansible_distribution == "Ubuntu"
