---
- hosts: lb
  become: yes
  gather_facts: true

  task:
  - name: install the list packages
    vars:
      packages:
        - name: wget
          required: true
        - name: elinks
          required: true
        - name: zip
          required: true
  - name: install the listed  {{ packages.name }} 
    yum:
      name: "{{ packages.name }}"
      state: present
    when: packages.required == true
