  ---
- hosts: db
  become: yes
  gather_facts: true
  
  vars:
    packages:
      - name: wget
        required: true
      - name: elinks
        required: true
      - name: zip
        required: true
  
  tasks:
  - name: install the listed packages...
    yum:
      name: "{{ packages.name }}"
      state: present
    when: 
      - "{{ packages.required }} == true"
