---
- hosts: ansimaster
  gather_facts: False
  become: yes
  ignore_errors: no
  vars: 
    My_Num: 0987654311
    Packs: ['vim', 'nano', 'wget', 'ntpd']
    Packss:
      - 'vim'
      - 'nano'
      - 'wget'
      - 'ntpd'
    web_servers: {'Apache': 'HTTPD', 'Web_Server': 'Tomcat'}
    web_serverss:
      - Apache: HTTPD
      - Web_Server: Tomcat
  tasks:
  - name: Print the values of data structure...
    debug:  #var=Packs
      var: Packs
    tags: varsp

  - name: Print the values in list formates with VAR... #NOT WORKING#
    debug:
      var:
        - "{{ Packs }}"
        #- Packss
        #- web_servers
        #- web_serverss

  - name: Print the values in list formates with MSG...
    debug:
      msg:
        - "{{ Packs }}"
        - "{{ Packss }}"
        - "{{ web_servers }}"
    tags: ftmsg

  - name: Print the First Values
    debug:
      var: Packss[0]
    tags: index

  - name: Print the values of KEYS
    debug:
      var: web_serverss.keys()
    tags: keys
