---
- hosts: ansimaster
  gather_facts: False
  become: yes
  ignore_errors: no
  vars: 
    My_Num: 0987654311
    Packs: ['vim', 'nano', 'wget', 'ntpd']
    Packss:
      - 'vim'
      - 'nano'
      - 'wget'
      - 'ntpd'
    web_servers: {'Apache': 'HTTPD', 'Web_Server': 'Tomcat'}
    web_serverss:
      - Apache: HTTPD
      - Web_Server: Tomcat
  tasks:
  - name: Print the values of data structure...
    debug: 
      var: Packs

  - name: Print the values in list formates
      var:
        - Packs
        - Packss
        - web_server
      #msg:
      #  - "{{ Packs }}"
       # - "{{ Packss }}"
        #- "{{ web_server }}"
