---
- hosts: ansimaster
  become: yes
  gather_facts: False

  vars:
    - x: 39
    - my_name: Roshan Munawar
    - my_num: 0987654321
    - MY_RMS: no  #false [OR] False

  vars_files:
    - variables.txt
    
  tasks:
  - name: Testing Datatypes and Variables...
    debug:
      msg:
        - "The Value of x is: {{ x }}"
        - "The Value of my_num: {{ my_num }} and type : {{ my_num | type_debug }}"
        - "The Value of my_name: {{ my_name }} and type : {{ my_name | type_debug }}"
        - "The Value of MY_RMS: {{ MY_RMS }} and type: {{ MY_RMS | type_debug }} "
    tags: data_vars

  - name: Print the variables from vars file...
    debug: var=my_name
    tags: staffout

  - name: Print the variables called "staff" and "faculty" from vars file...
    debug:
      msg:
        - "This is staff list: {{ staff }}"
        - "This is my faculty list: {{ item }}"
      loop: "{{ faculty }}"
    tags: staffout
