---
- hosts: ansimaster
  become: yes
  gather_facts: False

  vars:
    - x: 39
    - my_name: Roshan Munawar
    - my_num: 0987654321
    - MY_RMS: false # [OR] False
    
  tasks:
  - name: Testing Datatypes and Variables...
    debug:
      msg:
        - "The Value of x is: {{ x }}"
        - "The Value of my_num: {{ my_num }} and type : {{ my_num | type_debug }}"
        - "The Value of my_name: {{ my_name }} and type : {{ my_name | type_debug }}"
        - "The Value of MY_RMS: {{ MY_RMS }} and type: {{ MY_RMS | type_debug }} "
