---
- hosts: db
  become: yes
  gather_facts: true
  
  vars:
    var_name: roshanslab
  
  tasks:
  
  - name: Print debug variables of DB host..
    debug:
      var: ansible_facts
      
  - name: Print ansible_facts variables of DB host..
    debug:
      var: ansible_facts['default_ipv4']['address']
    when: 
      - ansible_facts['default_ipv4']['address'] == '172.31.127.70'
      - ansible_facts['default_ipv4']['macaddress'] == '02:94:d1:be:23:41'
    register: ansiblefact
    tags: ansifacts
    
  - name: Print when failed to meet the conditions
    debug: msg="{{ ansiblefact }}"
    failed_when: "'Conditional result was False' in ansiblefact"
    tags: ansifacts
