---
- hosts: db
  become: yes
  gather_facts: true
  
  vars:
    var_name: roshanslab
  
  tasks:
  
  - name: Print debug variables of DB host..
    debug:
      var: ansible_facts
      
  - name: Print ansible_facts variables of DB host..
    debug:
      var: ansible_facts['default_ipv4']['address']
