---
- hosts: web
  gather_facts: True
  become: yes

  tasks:
  - name: Print the facts values
    ansible.builtin.shell: bash --version
    register: listout

  - debug: var=listout.stdout.split(\n)
  
  - debug: 
      msg:
        - "{{ listout }}"
  
      
