---
- hosts: web
  gather_facts: True
  become: yes

  tasks:
  - name: Print the facts values
    ansible.builtin.shell: ls -ltrh /tmp
    register: listout
  - debug: 
      msg:
        - "{{ listout }}"
  
      
