---
- hosts: web
  gather_facts: True
  become: yes

  tasks:
  - name: Print the facts values
    ansible.builtin.shell: bash --version
    register: listout

  - set_fact: 
      bash_version: "{{ listout.stdout.split('\n')[0].split()[4] }}"

  - debug: var=bash_version
  
  - debug: 
      msg:
        - "{{ listout }}"
  
      
