---
- hosts: web
  become: yes
  gather_facts: yes
  
  tasks:
  - name: Checking the HTTPD Service...
    shell: systemctl status httpd.service -f
    register: httpdoutput
  - debug:
      msg: "{{ httpdoutput.stdout_lines }}"
 
  - name: SKIPPED WHEN HTTPD is RUNNING :) 
    ansible.builtin.shell: echo "HTTPD-Service is not running so please restart httpd service..."
    when: httpdoutput.rc == "3"
