---
- hosts: web
  become: yes
  gather_facts: yes
  
  tasks:
  - name: Checking the HTTPD Service...
    shell: systemctl status httpd.service -f
    register: httpdoutput
  - debug:
      msg: "{{ httpdoutput.stdout_lines }}"
