---
- hosts: web #all
  become: yes
  gather_facts: false

  tasks:
    - name: Get Inventory_hostname details...
      debug: var=inventory_hostname[all] #inventory_hostname[all]
      tags: in_host

    - name: Get HostVars and print the values...
      debug: var=hostvars
      tags: ho_vars
