---
- hosts: web #all
  become: yes
  gather_facts: true

  tasks:
    - name: Get Inventory_hostname details...
      debug: var=inventory_hostname[all] #inventory_hostname[web]
      tags: in_host

    - name: Get HostVars and print the values...
      debug: #var=hostvars[inventory_hostname] #hostvars[web]
        msg: "{{ hostvars }}"
      tags: ho_vars

    - name: Get HostVars and print the values...
      debug: #var=ansible_facts
        #var: ansible_facts
        msg:
          - "The OS Family: {{ ansible_os_family }}"
          - "This is the FQDN: {{ ansible_nodename }}"
          - "This is the Node Name: {{ ansible_hostname }}"
          - "This is the IPV4 IP ADDRESS: {{ ansible_lo.ipv4.['address'] }}"
      tags: ansi_vars

