---
- hosts: web
  become: yes
  gather_facts: False

  vars:
    - newpassword: 123456
  
  tasks:
  - name: Check the filesystems
    stat:
      path: /etc/hosts
    register: filesystem
    tags: FSYS
  - debug:
      #msg: File ATTR {{ filesystem }}
      #msg: "File ATTR {{ filesystem }}"
      msg: "{{ filesystem }}"
    tags: FSYS
####
  - name: Create a file
    file:
      path: /tmp/roshan.txt
      state: touch
    tags: createfile
    
  - name: Check the file
    stat:
      path: /tmp/roshan.txt
    tags: createfile

  - name: Add text file in the file
    blockinfile:
      path: /tmp/roshan.txt
      block: Everything you need to know about Linux Automation with Ansible - Roshan
    tags: createfile

  - name: Read a file
    shell: cat /tmp/roshan.txt
    register: fileout
    tags: createfile
  - debug:
      msg: "{{ fileout }}"
    tags: createfile
    
  - name: Delete a file
    file: 
      path: /tmp/roshan.txt
      state: absent
    register: delfile
    tags: dfile
    
  - debug:
      msg: "{{ delfile }}"
    tags: dfile
#####
  - name: Create a Directory
    file:
      path: /opt/tomcat/
      state: directory
      mode: 755
      owner: root
      group: root
    tags: createdir

  - name: Download a Tomcat package
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.93/bin/apache-tomcat-8.5.93.tar.gz
      dest: /opt/tomcat/
      mode: 755
      owner: root
      group: root
    tags: createdir

  - name: List the Tomcat file
    shell: ls -ltrh /opt/tomcat/
    register: lstomcat
    tags: createdir
  - debug:
      msg: "{{ lstomcat }}"
    tags: createdir
#####
  - name: Create a USER and Change a password
    user:
      name: "{{ item }}"
      update_password: always
      password: "{{ newpassword|password_hash('sha512') }}" # -e newpassword
    loop:
      - jack
      - andy
      - sandy
      - carl
    register: cuser
    tags: createuser
  - debug:
      msg: "{{ cuser }}"
    tags: createuser
#####
  - name: Find a process and kill it
    ignore_errors: yes
    shell: "ps -few | grep top | awk '{print $2}'"
    register: running_process
    tags: RP
  - debug:
      msg: "{{ running_process.stdout_lines }}"
    tags: RP
 #- name: Kill running processes
  #ignore_errors: yes
  #shell: "kill {{ item }}"
  #with_items: "{{ running_process.stdout_lines }}"
    
#####











    
