---
- hosts: web
  become: yes
  gather_facts: True

  tasks:
  - name: Check the filesystems
    stat:
      path: /etc/hosts
    register: filesystem
    tags: FSYS
  - debug:
      msg: File ATTR {{ filesystem }}
    tags: FSYS
