---
- hosts: web
  become: yes
  gather_facts: False

  tasks:
  - name: Check the filesystem
    stat:
      path: /etc/hosts
    register: fs
    
  - debug:
      msg: File Attr {{ fs }}
    tags: FS
