---
- hosts: web
  become: yes
  gather_facts: False

  tasks:
  - name: Check the filesystem
    stat:
      path: /etc/hosts
    register: filesystem
    
  - debug:
      msg: "File Attr {{ filesystem.split[-1] }}"
    tags: FSYS
