---
- hosts: web
  become: yes
  gather_facts: True

  tasks:
  - name: Check the filesystems
    stat:
      path: /etc/hosts
    register: filesystem
    
  - debug:
      msg: "{{ filesystem }}"
    tags: FSYS
