---
- hosts: ansimaster
  become: yes
  gather_facts: True

  tasks:
  - name: What is my ansible_hostname
    debug: 
      var: "{{ groups['all'] }}"
    tags: allhosts

  - name: Print All Hosts One By One...
    shell: ping -c 2 {{ item }}
    with_items: "{{ groups['web'] }}"
    register: shellout
    tags: allgroup

  - debug:
      msg: "{{ shellout.stdout }}"
    tags: allgroup
