---
- hosts: localhost
  become: yes
  gather_facts: True
  ignore_errors: True

  tasks:
  - name: What is my ansible_hostname
    debug: 
      var: "{{ groups['all'] }}"
    tags: allhost

  - name: Print All Hosts One By One...
    shell: ping -c 2
    #shell: ping -c 1 {{ item }}
    #with_items: "{{ groups['globe'] }}"
    register: shellout
    tags: allgroup

  - debug:
      msg: "{{ item.stdout_lines }}"
    loop: "{{ shellout.results }}"
    tags: allgroup

  - name: Print All Hosts One By One...
    shell: echo "My Name is {{ item }}"
    with_items: "{{ groups['web'] }}"
    register: shellecho
    tags: allhosts
  
  - debug:
      msg: "{{ item.stdout_lines }}"
    loop: "{{ shellecho.results }}"
    tags: allhosts
