---
- hosts: all
  become: yes
  gather_facts: True

  tasks:
  - name: What is my inventory_hostname
    debug: var={{inventory_hostname}}

  - name: What is my ansible_hostname
    debug: var={{ansible_hostname}}
