---
- hosts: globe
  become: yes
  gather_facts: True
  ignore_errors: True

  tasks:
  ##IMP##
  - name: Print the INV HOSTNAME
    debug: 
      msg: this is my inventory_hostname
    tags: inv_hosts
    
  - name: Print the INV HOSTNAME
    debug: 
      var=inventory_hostname
    tags: inv_hosts1
    
  - name: Print the INV HOSTNAME
    debug: 
      msg: "This is my {{ inventory_hostname }}"
    tags: inv_hosts2

  - name: Print the INV HOSTNAME
    debug: 
      msg: "This is my {{ inventory_hostname_short }}"
    tags: inv_hosts3

  - name: Print the INV HOSTNAME
    debug: 
      var=groups
    tags: inv_hosts4

  - name: Print the INV HOSTNAME
    debug: 
      msg: "This is my {{ groups }}"
    tags: inv_hosts5

  - name: Print the INV HOSTNAME
    debug: 
      msg: "This is my {{ groups.keys() }}"
    tags: inv_hosts6

  - name: Print the INV HOSTNAME
    debug: 
    var=groups
    tags: inv_hosts7
    
  - name: What is my ansible_hostname
    debug: 
      var: "{{ groups['all'] }}"
    tags: allhost

  - name: Print All Hosts One By One...
    #shell: ping -c 2
    shell: ping -c 1 {{ item }}
    with_items: "{{ groups['globe'] }}"
    register: shellout
    tags: allgroup

  - debug:
      msg: "{{ item.stdout_lines }}"
    loop: "{{ shellout.results }}"
    tags: allgroup

  - name: Print All Hosts One By One...
    shell: echo "My Name is {{ item }}"
    with_items: "{{ groups['web'] }}"
    register: shellecho
    tags: allhosts
  
  - debug:
      msg: "{{ item.stdout_lines }}"
    loop: "{{ shellecho.results }}"
    tags: allhosts

