---
- hosts: all
  become: yes
  gather_facts: True

  tasks:
  - name: What is my ansible_hostname
    debug: 
      var: "{{ groups['all'] }}"

  - name: Print All Hosts One By One...
    shell: echo "My Host Name is {{ item }}"
    with_items: "{{ groups['all'] }}"
