---
- hosts: db
  gather_facts: False

  tasks:
  
  - name: Check if rpm is already installed...
    yum:
      list: wget
    # If not installed yum_list.results[*].yumstate != installed
    register: yum_list
    tags: yuml

  - name: Conditionally Checking The Package Is Installed or not...
    debug:
      msg: "Not installed"
    when: yum_list.results | selectattr("yumstate", "match", "installed") | list | length == 0
    tags: yuml
