#!//usr/bin/ansible-playbook
- hosts: db
  gather_facts: False

  tasks:
  
  - name: Check if rpm is already installed...
    yum:
      list: wget
    # If not installed yum_list.results[*].yumstate != installed
    register: yum_list
    tags: yuml

  - name: Checking The Package Is Installed or not...
    debug:
      msg: "{{ yum_list }}"
    tags: yuml

  - name: Checking The Package Is Installed...
    debug:
      msg: 
        - "{{ yum_list.results.name }}"
        - "{{ yum_list.results.nevra }}"
        - "{{ yum_list.results.yumstate }}"
    when: "'installed' in yum_list.results"
    tags: yuml
    
  - name: Conditionally Checking The Package Is Installed or not...
    debug:
      msg: "Not installed"
    when: yum_list.results | selectattr("yumstate", "match", "available") | list | length != 0
    tags: yumnotins

  - name: set package version
    set_fact:
      package_name_version: "{{ yum_list.results|selectattr('yumstate','equalto','installed')|map(attribute='version')|list|first }}"
    tags: yumins
