- hosts: ansimaster
  remote_user: cloud_user
  gather_facts: False
  
  tasks:
  
  - name: Git pull task after git repo updates
    git:
      repo: https://github.com/roshanahtina/ansible.git
      dest: /home/cloud_user/repos/ansible/Ansible-2023/ansible
      refspec: '+refs/pull/*:refs/head/*'
    register: pullresults
  - debug: 
      msg: "Output Pull Info {{ pullresults }}"
