---
- hosts: ansi-2
  remote_user: ec2-user
  become: yes
  become_method: sudo
  gather_facts: false

  tasks:
  - file:
      path: /var/www/html/index.html
      state: touch
      mode: "u=rw,g=r,o=r"
  - lineinfile:
      path: /var/www/html/index.html
      line: '<h1> Welcome to the Ansi world </h1>'
    register: "STDOUT of file creation"
  - debug:
      msg: "STDOUT of file creation {{ STDOUT of file creation }}"
