---
- hosts: ansi_2 
  remote_user: ec2-user
  become: yes
  become_method: sudo
  gather_facts: false


  tasks:
  - name: Installing HTTPD server
    yum:
      name: httpd
      state: latest

  - name: Restarting Web Server
    service:
      name: httpd
      state: started
    register: output
  - debug:
      msg: "SHOW RESTART OUTPUT {{ output }}"

  - name: Installing elinks packages
    yum:
      name: elinks
      state: latest
  
  - name: Creating a file called "Index.html"
    file:
      path: /var/www/html/index.html
      state: touch
    lineinfile:
      path: /var/www/html/index.html
      line: "<h1> Welcome to the Ansi world </h1>"

  - debug:
      msg: "Line creation file error:" 
 
- hosts: ansi_1
  remote_user: ec2-user
  become: yes
  become_method: sudo
  gather_facts: false

  handlers:
    - name: Restarted The Web Server
      service:
        name: httpd
        state: started
      listen: "Restarted The Web Server"

  tasks:
  - name: Installing WEB server and Calling handlers signal
    yum:
      name: httpd
      state: latest 
    notify: "Restarted The Web Server"
    register: restartlogs

  - debug:
      msg: "Resating logs {{ restartlogs }}"
 
  - name: Creating a file called "Index.html" 
    file:
      path: /var/www/html/index.html
      state: touch
    lineinfile: 
      path: /var/www/html/index.html
      state: touch
      line: "<h1> Welcome to the Ansi world </h1>"

  - debug:
      msg: "Line creation file error:"
