---
- hosts: ansiclients
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: true

  tasks:
  - name: "Gathering the ec2-user information"
    user: 
      name: jsmith
      password: jsmith@123
      comment: "Admin" #####jsmith:x:1002:1002:Admin:/home/jsmith:/bin/bash####
    register: useroutput
  - debug:
      msg: "Output of the user creation called JSMITH {{ useroutput }}"
