---
- hosts: all
  remote_user: ec2-user
  become: yes
  become_method: sudo
  gather_facts: true

  tasks:
    - name: "Gathering the ec2-user information"
        user: jsmith
        comment: "Admin"
