---
- hosts: ansiclients
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: true

  tasks:
  - name: "Gathering the ec2-user information"
    user: 
      name: rmunavar
      password: "$6$testuser123$17Dmg0Aa6wmCqSlm12pkbxLtGYZC7lodFnbSMQdlFPzVqqhKJgOddXU7QgIsOXTp9zzmtGgi42DVvbtxe.UlN1" ## ansible all -i localhost, -m debug -a "msg={{ 'mypassword' | password_hash('sha512', 'testuser123') }}"
      comment: "Admin" #####jsmith:x:1002:1002:Admin:/home/jsmith:/bin/bash####
    register: useroutput
  - debug:
      msg: "Output of the user creation called JSMITH {{ useroutput }}"
