---
- hosts: ansiclients
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: true

  tasks:
  - name: "Gathering the ec2-user information"
    user: 
      name: rmunavar
      password: "{{ password }}" 
      comment: "Admin"
    register: useroutput
  - debug:
      msg: "Output of the user creation called RMUNAVAR {{ useroutput }}"
