---
- hosts: ansi_1
  remote_user: ec2-user
  become: yes
  become_method: sudo
  gather_facts: fales
  
  tasks:
  - name: Get files
    get_url:
      url: http://{{item}}/index.html
      dest: /tmp/{{item}}
    with_items:
      - "{{ inventory_hostname['ansi_1'] }}"
      
