---
- hosts: all
  remote_user: ec2-user
  become: yes
  become_method: sudo
  gather_facts: fales

  handlers:
    - name: webserver HTTPD restart
      service:
        name: httpd
        state: started
      #listen: "webstarted"
    - debug:
        msg: "Handlers errors messages"

  tasks:
  - name: Installing HTTPD on All server
    yum:
      name: httpd
      state: latest
    notify:
    - webserver HTTPD restart
  - debug:
      msg: "HTTPD INstalling Logs"

  - name: Creating index.html file
    file:
      path: /var/www/html/index.html
      state: touch
      mode: 0644

  - name: Inserting hello worlds words in a file
    lineinfile:
      path: /var/www/html/index.html
      line: "<h1> Welcome TO The WEB WORLD!! </h1>"

  - name: Get files
    get_url:
      url: http://{{item}}/index.html
      dest: /tmp/{{item}}
    with_items:
      - "{{ groups['ansi_1'] | join (' ')}}"
      - "{{ groups['ansi_2'] | join (' ')}}"
