---
# Clone a Git repo by using git_url and Setting password using valut

- hosts: ansiclients
  remote_user: ansible
  become_method: sudo
  gather_facts: true

  tasks:
  
  - name: Cloning a REPO
    git:
      repo: https://github.com/roshanahtina/test.git
      dest: /tmp/gitrepo
      archive: /tmp/gitrepo.zip
