---
- name: This is the yml play_file of combination of limit and changed when and failed when
  hosts: ansi22
  become: yes
  gather_facts: yes
  
  tasks:
  - name: Ignore errors directive placed
    command: /bin/flase
    ignore_errors: yes ##To Avoid - fatal: FAILED! => {"changed": false, "cmd": "/bin/flase", "msg": "[Errno 2] No such file or directory", "rc": 2}
    tags:
      - ignoreerrors
    
  - name: Failed and Changed When Condition on same play
    command: /etc/ansible/failed_changed_condition.sh #what To check the condition
    register: scriptout
    changed_when: '"CHANGED" changed in scriptout.stdout'
    failed_when: '"FAILED" failed in scriptout.stdout'
    #tags:
    #  - condition_change_failed
  - debug: 
      msg: "Output {{ scriptout }}"
  
