---
- name: This is the yml play_file of combination of limit and changed when and failed when
  hosts: ansiclients
  become: yes
  gather_facts: yes
  
  tasks:
  - name: Ignore errors directive placed
    command: /bin/flase
    ignore_errors: yes ##To Avoid - fatal: FAILED! => {"changed": false, "cmd": "/bin/flase", "msg": "[Errno 2] No such file or directory", "rc": 2}
    tags:
      - ignoreerrors
    
  - name: Failed and Changed When Condition on same play
    command: /bin/sh /etc/ansible/failed_changed_condition.sh what
    register: scriptout
    changed_when: '"CHANGED" When changed is scriptout.stdout'
    failed_when: '"FAILED" When failed is scriptout.stdout'
    tags:
      - condition_change_failed
