---
- hosts: all
  remote_user: ec2-user
  become: yes
  become_method: sudo
  gather_facts: true
  
  tasks:
  - name: lookup the ssh key file
    command: echo "{{ ssh_keys }}"
    register: findingthepubkeys
  - demsg: msg="output {{ findingthepubkeys }}"
    vars:
      ssh_keys:
      - "{{lookup('file', '/home/jsmith/.ssh/id_rsa.pub') }}"
