---
- name: Loops is replaced with with_items
  hosts: ansiclients
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: true
  serial: 
    - 1
    - 2
    - 2
  
  #vars_files:
  #  - vars.yml
  
  tasks:
  - name: Installing list of packages with loop style
    yum:
      name: "{{ item }}"
      state: latest
    loop:
      - wget
      - zip
      - git
      - httpd
      - ntp
      - mariadb
      
  - name: Starting the service using the service module
    service:
      name: "{{ item }}"
      state: started
    loop: "{{ service_lists }}"
    tags:
      - servicelist
