---
- hosts: ansiclients
  remote_user: ansible
  become: true
  become_method: sudo
  gather_facts: true
  
  tasks:
  - name: Create A File using vars
    file:
      path: "{{ magic_var }}"
      state: touch
      
  - name: Copy a group hosts name in a newly created file
    lineinfile:
      path: "{{ magic_var }}"
      line: "{{ groups['all'] | join (' ')}}"
  - debug: msg="OutPut of the Line in a file"
  
  #- name: fateching a hostname
  #  lineinfile:
  #    path: "{{ magic_var }}"
  #    line: "{{ groups['ansi_1'] | join (' ')}}"
  #- debug:
  #    msg: "Output of the hostnames entries"
