---
# Package installation on Ansiclietns

- hosts: ansiclients
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: true
  
  tasks:
  
  - name: Installing multiple packages with using package moule
    package:
      name: "{{ item }}"
      state: absent
    with_items:
      - git
      - httpd
      - mysql
      - zip
    register: echo
    
  - debug: msg="Output:  {{ echo }}"
  
#  - name: Un-Installing a GIT package
#    yum:
#      name: git
#      #state: absent
#      state: latest
#  - debug: msg="Package is successfully un-installed "
