---
# Package installation on Ansiclietns

- hosts: ansiclients
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: true
  
  tasks:
  
  - name: Installing multiple packages with using package moule
    package:
      name: "{{ item }}"
      state: absent
    with_items:
      - mysql-server
      - httpd
      - php*
    register: echo
    
  - debug: msg="Output {{ echo }}"
  
 # - name: Install the packages with variables
    var:
      packages:
        - httpd
        - binutils
        - glibc
        - ksh
        - libaio
        - libXext
        - gcc
        - make
        - sysstat
        - unixODBC
        - grunt
    
  - name: Install the packages with yum
    list: "{{ item }}"
    register: output
    with_items: "{{ packages }}"
    
  - debug: msg="output {{ output }}"
    
    
  
#  - name: Un-Installing a GIT package
#    yum:
#      name: git
#      #state: absent
#      state: latest
#  - debug: msg="Package is successfully un-installed "
