---
# Package installation on Ansiclietns

- hosts: ansiclients
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: true
  
  tasks:
  
  - name: Installing a GIT package
    yum:
      name: git
      state: latest
      
  - debug: msg="Package is successfully installed "
