---  # Package installation on Ansiclietns
- hosts: ansi666
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: true
  vars:
    packages:
      - httpd
      - binutils
      - glibc
      - ksh
      - libaio
      - libXext
      - gcc
      - make
      - sysstat
      - unixODBC
      - grunt
  
  tasks:
  - name: Installing multiple packages with using package module
    package:
      name: "{{ item }}"
      state: absent
    with_items:
      - mysql-server
      - httpd
      - php*
    register: echo
    
  - debug: msg="Output {{ echo }}"
  
  - name: Install the packages with variables
    yum:
      list: "{{ item }}"
      state: installed
    with_items: "{{ packages }}"
    register: output
    
    
  - debug: msg="output {{ output }}"
    
    
  
#  - name: Un-Installing a GIT package
#    yum:
#      name: git
#      #state: absent
#      state: latest
#  - debug: msg="Package is successfully un-installed "
