---
# Package installation on Ansiclietns

- hosts: ansiclients
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: true
  
  tasks:
  
  - name: Un-Installing a GIT package
    yum:
      name: git
      state: absent
      
  - debug: msg="Package is successfully un-installed "
