---
- hosts: all
  remote_user: ec2-user
  become: yes
  become_method: sudo
  gather_facts: true
  
  tasks:
  - name: getting facts informations
    template:
      src: /home/ec2-user/ansible-training/template.ji2
      dest: /home/ec2-user/template.txt
  - debug: msg="Template dest output:"
        
