---
- hosts: ansi-clients
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: true

  tasks:
  - name: Uninstalling HTTPD on Ansible Servers
    yum:
      name: httpd
      state: absent
   register: httpdUnInstallop
      
  - debug: msg="Output of starting a HTTPD Service {{ httpdUnInstallop }}"
