---
- hosts: all
  remote_user: ec2-user
  become: yes
  become_method: sudo
  gather_facts: true

  tasks:
  - name: Uninstalling HTTPD on Ansible Servers
    yum:
      name: httpd
      state: absent
      
  - debug: 
      msg: "UnInstalling Apache WebServer:"
