---
- hosts: all
  remote_user: ec2-user
  become: yes
  become_method: sudo
  gather_facts: true

  tasks:
  - name: Creation of bunch of users
    user:
      name: {{ item }}
      groups: wheel
    loops:
      - jon
      - man
      - rose
      - jack
      - paul
      
