---
- hosts: all
  remote_user: ec2-user
  become: yes
  become_method: sudo
  gather_facts: true

  tasks:
  - name: Create a 2048-bit SSH key for user jsmith in ~jsmith/.ssh/id_rsa
    user:
      name: jsmith
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
    register: Outputofuseradd
  - debug: msg="O/P of Usedadd {{ Outputofuseradd }}"
# - name: Remove the user 'johnd'
#   user:
#     name: jsmith
#     state: absent
#     remove: yes
#   register: result
  - debug: msg="Output of userdell {{ result }}"
 #- name: Creation of bunch of users
 #  user:
 #    name: "{{ item }}"
 #    state: present
 #  loop: "{{ user.lst }}"
    #with_items: 
    # - jon
    # - man
    # - rose
    # - jack
    # - paul
# - name: Create a 2048-bit SSH key for user jsmith in ~jsmith/.ssh/id_rsa
#   user:
#     name: jsmith
#     generate_ssh_key: yes
#     ssh_key_bits: 2048
#     ssh_key_file: .ssh/id_rsa
