---
# - vars_file: /home/ansible/varsfiles.txt

- hosts: testclients
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: true
  
  vars_files: 
    - /etc/ansible/vars/varsfiles.txt
    
  tasks:
  - name: check the status of following commands
    command: ls -ltrh /var/log
    check_mode: "{{ check }}"
    #check_mode: no
    register: echo
  
  - debug: msg="Output {{ echo }}"
      
#- hosts: localhost
#  become: yes
#  vars_files:
#         - /home/ansible/vault
#
#  tasks:
#          - name: create a file and putting a secret init
#            lineinfile:
#                    path: /home/ansible/secret.txt
#                    create: yes
#                    line: "{{ secret }}"
#            no_log: true
#            register: vaultout
#
#          - debug: msg="{{ vaultout }}"

# ansible-vault encrypt --vault-id dev@prompt vault # vault is file
# ansible-playbook -i /etc/ansible/inv.ini vault_file.yml   --vault-password-file=password.txt # password.txt is plain text file
# ansible-playbook -i /etc/ansible/inv.ini vault_file.yml --vault-id=dev@prompt
