---
# - vars_file: /home/ansible/varsfiles.txt

- hosts: testclients
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: true
  
  vars_files: 
    - /etc/ansible/vars/varsfiles.txt
    
  tasks:
  - name: check the status of following commands
    command: ls -ltrh /var/log
    #check_mode: "{{ check }}"
    check_mode: no
    register: echo
  
  - debug: msg="Output {{ echo }}"
      
