---
# handlers file for role_php_site_1
- name: 'apache restart'
  service:
    name: httpd
    state: restarted
  register: restartapache
- debug: msg="restarted output {{ restartapache }}"

- name: 'mysql restart'
  service:
    name: mysql
    state: restarted
  register: restartmysqld
- debug: msg="restarted mysql output {{ restartmysqld }}"

- name: 'yum clean'
  command: yum clean all
