service_name: httpd
service_status: status
service_start: started
service_restart: restarted
service_stop: stopped
service_reload: reloaded
httpd_status: dead
httpd_status_dead: "Active: inactive (dead)"
