user_groups:
  - staff
  - students
  - faculty
staff:
  - john
  - henery
  - amanda
  - marshal
  - hank
  - nancy
  - kate
  - jim
  - stan
  - megan
  - emily
  - jack
  - aaron
students:
  - frank
  - karen
  - alexa
  - cathrine
  - dave
  - chuck
  - eric
  - lauren
  - beth
  - nicole
  - jen
  - greg
  - hugo
  - jessica
  - johnson
  - ashley
  - keith
  - landon
  - marge
  - mac
  - ned
  - lisa
faculty:
  - zach
  - yancy
  - walter
  - thomas
  - stacy
  - rene
  - qunicy
  - penny
