---
- name: Copying the conf file to the path
  template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/
  register: results
  notify:
    - restart apache server
- debug: msg="Output {{ results }}"
    
- name: Copying index.html file to the path
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  register: result
  notify:
    - restart apache server
- debug: msg="output {{ result }}"

#- name: Removing file called index.html
#  file:
#    path: /var/www/html/index.html.j2
#    state: absent
#  register: echo
#- debug: msg="Output {{ echo }}"  

