---
- name: Copying the conf file to the path
  copy:
    src: httpd.conf
    dest: /etc/httpd/conf/
  notify:
    - restart apache server
    
- name: Copying index.html file to the path
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify:
    - restart apache server
