---

  
- name: Adding a Repository to download a MariaDB packaegs
  yum_repository:
    name: MariaDB
    description: Mariadb YUM repo
    baseurl: http://yum.mariadb.org/10.3/centos7-amd64
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: yes
  notify: yum clean
  register: installRepo
- debug: msg=" Output of the Repo installation {{ installRepo }}"
    
- name: Wget Python 3.7
    - get_url:
        url: https://www.python.org/ftp/python/3.7.4/Python-3.7.4.tgz
        dest: /tmp
    - unarchive:
        src: /tmp/Python-3.7.4.tgz
        dest: /tmp/
    - make:
        chdir: /tmp/Python-3.7.4
        target: altinstall
    - command: 'python3.7 -V'
  register: pythoninstallation
  
- debug: msg="Otput {{ pythoninstallation }}"
    
- name: pip upgrade
  command: 'pip install --upgrade pip'
  register: outputpip
- debug: msg="Output stdout {{ outputpip.stdout }}"
    
- name: Install mysql python package
  pip:
    name: "{{ pippackages }}"
  register: outputpippack
- debug: msg="Output stdout {{ outputpippack.stdout }}"

- name: Installing mariadb
  yum:
    name: "{{ mysqlpackages }}"
    state: latest
    update_cache: yes
  #with_items:
  #  - "{{ mysqlpackages }}"
  notify: mysql restart
  register: installmariadb
   
- debug: msg=" Output of the mariadb installation {{ installmariadb }}"

- name: Creating a Mysql User  
  mysql_user:
    #login_user: "{{ mysqluser }}"
    #login_password: "{{ mysqlpassword }}"
    name: "{{ mysqluser }}"
    password: "{{ mysqlpassword }}"
    priv: '*.*:ALL,GRANT'
    state: present
  register: mysqluser
  
- debug: msg="Output Mysql User Creation {{ mysqluser }}"

- name: Creating a Mysql Databases
  mysql_db:
    name: "{{ mysqldatabase }}"
    login_user: "{{ mysqluser }}"
    login_password: "{{ mysqlpassword }}"
    state: present
    priv: '*.*:ALL,GRANT'
  register: mysqldatabase
  
- debug: msg="Output mysqldatabases {{ mysqldatabase }}"

#- mysql_info:
#    login_user: "{{ mysqluser }}"
#    login_password: "{{ mysqlpassword }}"
#    filter: version
#  register: mysqlversion
#  
#- debug: msg="Output {{ mysqlversion }}"
  
  
