---
- name: Installing mariadb
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - {{ mysqlpackages }}
  register: installmariadb
- debug: msg=" Output of the mariadb installation {{ installmariadb }}"
